#!/usr/bin/env python3
"""Build src/story/narration.js from the recitation's timestamp JSON.

  python3 tools/narration.py <timestamps.json>

The audio in assets-src/web/audio is the recording with its first OFFSET seconds of music cut
(ffmpeg -ss 40 ... afade in), so every time here is shifted by -OFFSET. Each chapter gets:
  t0     when its shot begins (audio seconds), inside the pause before its first word
  cue    [first word start, last word end]
  chars  for every Han character of the chapter's `orig`, [start, end] of its word
"""
import json, re, sys, difflib, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OFFSET = 40.0
DURATION = 247.98          # of the trimmed file
LEAD = 1.0                 # the shot begins this long before its first word...
AFTER = 0.25               # ...but not before the previous line has finished

# which recorded lines each chapter speaks (indices into the cue list)
CUES = [[0], [1], [2, 3], [4, 5], [6, 7], [8], [9], [10], [11], [12, 13], [14], [15], [16], [17, 18], [19],
        [20, 21, 22], [23], [24, 25], [26, 27, 28], [29, 30, 31, 32, 33], [34, 35, 36], [37], [38, 39], [40],
        [41, 42, 43], [44, 45, 46], [47], []]
# the two long musical pauses are split by hand (original times):
#   after 豁然开朗 the reveal holds, then 平旷 glides over the basin until its words come
#   after 不足为外人道也 he climbs away, then 志之 begins before 既出
T0_OVERRIDE = {10: 116.0, 22: 234.5, 27: 284.4}

han = lambda s: [c for c in s if '一' <= c <= '鿿']


def main(src):
    cues = json.load(open(src, encoding='utf-8'))['cues']
    js = (ROOT / 'src/story/chapters.js').read_text(encoding='utf-8')
    origs = re.findall(r"orig: '([^']*)'", js)
    assert len(origs) == len(CUES), (len(origs), len(CUES))
    out = []
    for i, (orig, ids) in enumerate(zip(origs, CUES)):
        words = [w for k in ids for w in cues[k]['words']]
        # one entry per Han character of the recording (a word may carry trailing punctuation)
        rec = []
        for w in words:
            cs = han(w['text'])
            for j, c in enumerate(cs):
                d = (w['end'] - w['start']) / len(cs)
                rec.append((c, w['start'] + j * d - OFFSET, w['start'] + (j + 1) * d - OFFSET))
        want = han(orig)
        times = [None] * len(want)
        sm = difflib.SequenceMatcher(a=want, b=[r[0] for r in rec], autojunk=False)
        for a, b, n in sm.get_matching_blocks():
            for k in range(n): times[a + k] = [round(rec[b + k][1], 2), round(rec[b + k][2], 2)]
        # a character the reader said differently (无复 for 不复) takes its neighbours' time
        for k in range(len(times)):
            if times[k] is None:
                prev = next((times[j] for j in range(k - 1, -1, -1) if times[j]), None)
                nxt = next((times[j] for j in range(k + 1, len(times)) if times[j]), None)
                s = prev[1] if prev else (nxt[0] if nxt else 0)
                e = nxt[0] if nxt else s + 0.4
                times[k] = [round(s, 2), round(max(e, s + 0.1), 2)]
        cue = [round(rec[0][1], 2), round(rec[-1][2], 2)] if rec else None
        out.append({'cue': cue, 'chars': times})
    # when each shot begins
    for i, ch in enumerate(out):
        if i in T0_OVERRIDE: t0 = T0_OVERRIDE[i] - OFFSET
        elif i == 0: t0 = 0.0
        else:
            prev_end = next(o['cue'][1] for o in reversed(out[:i]) if o['cue'])
            t0 = max(prev_end + AFTER, ch['cue'][0] - LEAD)
        ch['t0'] = round(t0, 2)
    lines = ['// generated by tools/narration.py from the recitation\'s timestamps: do not edit by hand',
             '// 李立宏 朗诵《桃花源记》; the audio has its first %gs of music trimmed, times are in the trimmed file' % OFFSET,
             "export const AUDIO = { src: new URL('../assets/audio/taohuayuan-lilihong.m4a', import.meta.url).href, duration: %g };" % DURATION,
             'export const NARRATION = [']
    for i, ch in enumerate(out):
        lines.append('  { t0: %s, cue: %s, chars: %s }, // %s' % (ch['t0'], json.dumps(ch['cue']), json.dumps(ch['chars'], separators=(',', ':')), origs[i][:12]))
    lines.append('];')
    (ROOT / 'src/story/narration.js').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    for i, ch in enumerate(out):
        nxt = out[i + 1]['t0'] if i + 1 < len(out) else DURATION
        print('%2d %6.2f %6.2f  %s' % (i, ch['t0'], nxt - ch['t0'], origs[i][:14]))


if __name__ == '__main__':
    main(sys.argv[1])
